title: Cezary Pilaszewicz's Homepage
page-top-title: Cezary Pilaszewicz
top-section-bg-text: IT Security Specialist
home-subtitle: Cezary Pilaszewicz
copyright-text: '&copy; Cezary Pilaszewicz 2025. All Rights Reserved.'
